### ISSUE TITLE
Bug Report: Not working anymore

### ISSUE THREAD

**Issue by Piripe** [Friedshrimp-Studio-TW/Discord-Experiments#1]
Yesterday I updated to the version 1.1.0 and it was working.

But today, I can't see any experiments tab anymore. I tried to restart the plugin a couple of times, I think Discord fixed your last patch.

And when I run the code in the console manually, I didn't get any error
![image](https://user-images.githubusercontent.com/77517308/213714682-e00952c5-cdd3-42df-af5e-780b331f3278.png)

**Comment by VincentX0905** [comment]
yes
Discord update broke it
Wait me check new code to update it

**Comment by VincentX0905** [comment]
@Piripe now fixed plugins
you can go to [Here](https://raw.githubusercontent.com/vincentwang0905/DiscordExperiments/plugins/DiscordExperiments.plugin.js) download.
