### ISSUE TITLE
[BUG]: Betterdiscord crashes on restard

### ISSUE THREAD

**Issue by hummusaki** [Friedshrimp-Studio-TW/Discord-Experiments#2]
### Describe the bug | BUG描述

When importing the script into betterdiscord, it crashes the app on reload and the only fix is to comment out the code

### Version | 版本

V1.2.0

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過

**Comment by VincentX0905** [comment]
It working fine to me
![image](https://user-images.githubusercontent.com/76867533/216803395-a961ab46-e794-4880-bb92-d16963bed293.png)

If you turn on too many Discord Experiments funtion
May cause you to crash

Because these are **Experimental funtion**
Experimental funtion are not stable

**Comment by hummusaki** [comment]
I meant more for a userscript, with BandagedBetterDiscord

**Comment by VincentX0905** [comment]
@Apoc101 
It working fine to me
I have 49 plugins
please send devtool log to me...
![image](https://user-images.githubusercontent.com/76867533/218045813-ef87ad49-78b4-4d90-8931-d5b2b6b10a98.png)
![image](https://user-images.githubusercontent.com/76867533/218046255-aba53d7a-71fa-427a-8902-ddacc5516c1d.png)

**Comment by VincentX0905** [comment]
Hello~ @Apoc101 
Do you have any questions?

**Comment by VincentX0905** [comment]
No reply for a long time, closed!
