### ISSUE TITLE
[BUG]: plugin auto disable when click avatar

### ISSUE THREAD

**Issue by speedlorenzo12** [Friedshrimp-Studio-TW/Discord-Experiments#3]
### Describe the bug | BUG描述

for some reason the plugin disables itself when you click on the profiles to see the description (I don't even know how to explain it)
(discord canary)

### Version | 版本

1.4.0

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過

**Comment by VincentX0905** [comment]
@speedlorenzo12 
Please update to latest version(V1.5.0) and try it again~
If you still have problems, please try to install only this plugin.
Because I can't reproduce.

**Comment by speedlorenzo12** [comment]
Works thx

**Comment by VincentX0905** [comment]
You are welcome!
