### ISSUE TITLE
[BUG]:  BD Crashes instantly with plugin enabled

### ISSUE THREAD

**Issue by sneazy-ibo** [Friedshrimp-Studio-TW/Discord-Experiments#8]
### Describe the bug | BUG描述

Plugin crashes BD
<img width="2056" alt="image" src="https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/41344259/860f3db0-3fdf-4302-bb0e-873376e9745b">

### Version | 版本

V 0.0.99

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過

**Comment by VincentX0905** [comment]
I didn't find this problem
Please confirm whether the version you are using is Discord Stable
PTB or Canary not supported
![image](https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/76867533/ac0f049d-eae2-4e9b-9a7a-d7c98399646f)
