### ISSUE TITLE
[BUG]: DiscordExperiments checks the new version too often

### ISSUE THREAD

**Issue by Serega007RU** [Friedshrimp-Studio-TW/Discord-Experiments#9]
### Describe the bug | BUG描述

Hello, I noticed that the Discord Experiments plugin checks for a new version too often, it does it every second. It's too fast and not normal. Isn't it better to check the version every hour, for example?
https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/blob/9fcaa09ac809ce28423b1af631541b16d70d3948/DiscordExperiments.plugin.js#L40

### Version | 版本

1.6.0

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過
- [ ] If you have any questions, please join our Discord to ask first.(View Readme) | 有問題建議先加入我們Discord詢問(查看Readme)

**Comment by VincentX0905** [comment]
@Serega007RU Thanks for the suggestion. Changed.
